// src/layouts/components/Header.tsx
import type { AppDispatch } from '@/stores'
import type { IPasswordModal } from './UpdatePassword'
import { useRef } from 'react'
import { useDispatch } from 'react-redux'
import { useAliveController } from 'react-activation'
import { toggleCollapsed } from '@/stores/menu'
import { useNavigate } from 'react-router-dom'
import { useToken } from '@/hooks/useToken'
import { clearInfo } from '@/stores/user'
import { closeAllTab, setActiveKey } from '@/stores/tabs'
import { Modal, Dropdown, MenuProps } from 'antd'
import {
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  LogoutOutlined,
  FormOutlined,
  ExclamationCircleOutlined
} from '@ant-design/icons'
import Avatar from '@/assets/images/avatar.png'
import styles from '../index.module.less'
import Fullscreen from '@/components/Fullscreen'
import GlobalSearch from '@/components/GlobalSearch'
import Theme from '@/components/Theme'
import UpdatePassword from './UpdatePassword'
import Nav from './Nav'
import {useCommonStore} from "@/hooks/useCommonStore"

type IMenuKey = 'password' | 'logout'

function Header() {
  const dispatch: AppDispatch = useDispatch()
  const navigate = useNavigate()
  const [, , removeToken] = useToken()
  const { clear } = useAliveController()
  // 是否窗口最大化
  const passwordRef = useRef<IPasswordModal>(null)
  const {
    isCollapsed,
    isMaximize,
    username,
    nav
  } = useCommonStore();

  // 下拉菜单内容
  const items: MenuProps['items'] = [
    {
      key: 'password',
      label: (<span>修改密码</span>),
      icon: <FormOutlined className="mr-1" />,
    },
    {
      key: 'logout',
      label: (<span>退出登录</span>),
      icon: <LogoutOutlined className="mr-1" />,
    },
  ]

  /** 点击菜单 */
  const onClick: MenuProps['onClick'] = e => {
    switch (e.key as IMenuKey) {
      case 'password':
        passwordRef.current?.open()
        break

      case 'logout':
        handleLogout()
        break

      default:
        break
    }
  }

  /** 退出登录 */
  const handleLogout = () => {
    Modal.confirm({
      title: '温馨提示',
      icon: <ExclamationCircleOutlined />,
      content: '是否确定退出系统?',
      onOk() {
        dispatch(clearInfo())
        dispatch(closeAllTab())
        dispatch(setActiveKey(''))
        removeToken()
        clear()
           .then(r =>{}) // 清除keepalive缓存
        navigate('/login')
      }
    })
  }

  /** 右侧组件抽离减少重复渲染 */
  const RightRender = () => {
    return (
      <div className="flex items-center">
        <GlobalSearch />
        <Fullscreen />
        <Theme />
        <Dropdown
          className="min-w-50px"
          menu={{ items, onClick }}
        >
          <div
            className="ant-dropdown-link flex items-center cursor-pointer"
            onClick={e => e.preventDefault()}
          >
            <img
              src={Avatar}
              width={27}
              height={27}
              alt="头像"
              className="rounded-1/2 overflow-hidden object-cover bg-light-500"
            />
            <span className="ml-2 text-15px min-w-50px truncate">
              { username || 'south-admin' }
            </span>
          </div>
        </Dropdown>
      </div>
    )
  }

  /** icon渲染 */
  const IconRender = () => {
    return (
      <div
        className="text-lg cursor-pointer"
        onClick={() => dispatch(toggleCollapsed(!isCollapsed))}
      >
        { isCollapsed && <MenuUnfoldOutlined /> }
        { !isCollapsed && <MenuFoldOutlined /> }
      </div>
    )
  }

  return (
    <>
      <header
        className={`
          border-bottom
          flex
          items-center
          justify-between
          px-6
          py-6px
          box-border
          transition-all
          ${styles.headerDriver}
          ${isMaximize ? styles.none : ''}
        `}
      >
        <div className="flex item-center">
          <IconRender />

          <Nav
            className="ml-15px"
            list={nav}
          />
        </div>

        <RightRender />
      </header>

      <UpdatePassword passwordRef={passwordRef} />
    </>
  )
}

export default Header

// src/layouts/components/Header.vue
<template>
  <header
    class="h-40px flex items-center justify-between px-6 py-6px box-border transition-all"
   >
    <div class="flex items-center">
      <div class="flex items-center text-lg cursor-pointer" @click="toggleCollapsed">
        <MenuUnfoldOutlined v-if="isCollapsed" />
        <MenuFoldOutlined v-else />
      </div>
      <Nav
        className="ml-15px"
        :list="nav"
      />
    </div>

    <div class="flex items-center">
      <GlobalSearch />
      <Fullscreen />
      <Theme />
      <Dropdown class="min-w-50px">
        <div class="ant-dropdown-link flex items-center cursor-pointer" @click.prevent>
          <img
            class="rounded-1/2 overflow-hidden object-cover bg-light-500"
            :src="Avatar"
            :width="27"
            :height="27"
            alt="头像"
          >
          <span class="ml-2 text-15px min-w-50px truncate">{{ username || 'south-admin' }}</span>
        </div>
        <template #overlay>
          <Menu @click="onClickDropdown">
            <MenuItem :key="Dropdowns.logout">
              <LogoutOutlined class="mr-1" />
              <span>退出登录</span>
            </MenuItem>
          </Menu>
        </template>
      </Dropdown>
    </div>
  </header>
</template>

<script lang="ts" setup>
import { createVNode, nextTick } from 'vue';
import { useRouter } from 'vue-router';
import { useToken } from '@/hooks/useToken';
import { useTabStore } from '@/stores/tabs';
import { useUserStore } from '@/stores/user';
import { storeToRefs } from 'pinia';
import { Modal } from 'ant-design-vue';
import {
  Menu,
  MenuItem,
  Dropdown,
  MenuProps
} from 'ant-design-vue';
import {
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  LogoutOutlined,
  FormOutlined,
  ExclamationCircleOutlined
} from '@ant-design/icons-vue';
import Fullscreen from '@/components/Fullscreen/index.vue';
import GlobalSearch from '@/components/GlobalSearch/index.vue';
import Theme from '@/components/Theme/index.vue';
import Github from '@/components/Github/index.vue';
import Avatar from '@/assets/images/avatar.png';
import Nav from './Nav.vue';
import TopMenu from "@/layouts/components/TopMenu.vue";

// 下拉菜单枚举
enum Dropdowns {
  update,
  logout
}

interface DefineEmits {
  (e: 'toggleCollapsed'): void;
  (e: 'onUpdatePassword'): void;
}

const emit = defineEmits<DefineEmits>();

interface DefineProps {
  isCollapsed: boolean;
  username: string;
}

withDefaults(defineProps<DefineProps>(), {});

const router = useRouter();
const tabStore = useTabStore();
const userStore = useUserStore();
const { removeToken } = useToken();
const { clearInfo } = userStore;
const {
  closeAllTab,
  clearCacheRoutes,
  setActiveKey
} = tabStore;
const { nav } = storeToRefs(tabStore);

/** 收缩菜单 */
const toggleCollapsed = () => {
  emit('toggleCollapsed');
};

/** 退出登录 */
const handleLogout = () => {
  Modal.confirm({
    title: '温馨提示',
    icon: createVNode(ExclamationCircleOutlined),
    content: '是否确定退出系统?',
    onOk() {
      removeToken();
      clearInfo();
      closeAllTab();
      clearCacheRoutes();
      setActiveKey('');

      nextTick(() => {
        router.push('/login');
      });
    }
  });
};

/**
 * 点击下拉菜单
 * @param e - 菜单点击属性
 */
const onClickDropdown: MenuProps['onClick'] = e => {
  switch ((e as { key: Dropdowns }).key) {
    // 退出登录
    case Dropdowns.logout:
      handleLogout();
      break;

    default:
      break;
  }
};
</script>
