// src/pages/admin/sysUser/index.tsx
import type { IFormData } from '#/form'
import type { IPagePermission, ITableOptions } from '#/public'
import type { FormFn } from '@/components/Form/BasicForm'
import { useCallback, useEffect, useRef, useState } from 'react'
import { createList, searchList, tableColumns } from './model'
import {  message } from 'antd'
import { useTitle } from '@/hooks/useTitle'
import { ADD_TITLE, EDIT_TITLE } from '@/utils/config'
import { UpdateBtn, DeleteBtn } from '@/components/Buttons'
import {
  createUser,
  deleteUser,
  getUserById,
  getUserPage,
  updateUser,
} from '@/servers/admin/user'
import {getAllRoles} from '@/servers/admin/role'
import  {getAllDept} from '@/servers/admin/dept'
import BasicSearch from '@/components/Search/BasicSearch'
import BasicModal from '@/components/Modal/BasicModal'
import BasicForm from '@/components/Form/BasicForm'
import BasicTable from '@/components/Table/BasicTable'
import BasicPagination from '@/components/Pagination/BasicPagination'
import PermissionWrapper from "@/components/PermissionWrapper"
import {useSelector} from "react-redux"
import {RootState} from "@/stores"
import {CheckPermission} from "@/utils/permissions"
import {IConstant} from "@/utils/constants"

// 当前行数据
interface IRowData {
  id: string;
}

// 初始化搜索
const initSearch = {
  pageIndex: 1,
  pageSize: 20
}

// 初始化新增数据
const initCreate = {
  status: '2'
}

function Page() {
  useTitle('用户管理')
  const searchFormRef = useRef<FormFn>(null)
  const createFormRef = useRef<FormFn>(null)
  const [isLoading, setLoading] = useState(false)
  const [isCreateLoading, setCreateLoading] = useState(false)
  const [isCreateOpen, setCreateOpen] = useState(false)
  const [createTitle, setCreateTitle] = useState(ADD_TITLE)
  const [createId, setCreateId] = useState('')
  const [createData, setCreateData] = useState<IFormData>(initCreate)
  const [pageIndex, setPageIndex] = useState(initSearch.pageIndex)
  const [pageSize, setPageSize] = useState(initSearch.pageSize)
  const [total, setTotal] = useState(0)
  const [tableData, setTableData] = useState<IFormData[]>([])
  const [roles, setRoles] = useState<IConstant[]>([])
  const [dept, setDept] = useState<IConstant[]>([])
  const userInfo = useSelector((state: RootState) => state.user.userInfo)

  // 权限
  const pagePermission: IPagePermission = {
    list: CheckPermission("admin:sysUser:query", userInfo.permissions),
    create: CheckPermission("admin:sysUser:add", userInfo.permissions),
    update: CheckPermission("admin:sysUser:update", userInfo.permissions),
    delete: CheckPermission("admin:sysUser:delete", userInfo.permissions),
  }

  /**
   * 点击搜索
   * @param values - 表单返回数据
   */
  const onSearch = (values: IFormData) => {
    setPageIndex(1)
    handleSearch({ page: 1, pageSize, ...values }).then(r=> {})
  }

  /**
   * 搜索提交
   * @param values - 表单返回数据
   */
  const handleSearch = useCallback(async (values: IFormData) => {
    try {
      setLoading(true)
      const { data: { data } } = await getUserPage(values)
      const { list, count } = data
      setTotal(count)
      setTableData(list)
    } finally {
      setLoading(false)
    }
  }, [])

  // 首次进入自动加载接口数据
  useEffect(() => {
    if (pagePermission.list) {
      handleSearch({ ...initSearch }).then(r => {})
      handleGetRoles().then(r => {}) // 请求角色信息
      handleGetDept().then(r => {}) // 请求部门列表
    }
  }, [handleSearch, pagePermission.list])

  /** 点击新增 */
  const onCreate = () => {
    setCreateOpen(true)
    setCreateTitle(ADD_TITLE)
    setCreateId('')
    setCreateData(initCreate)
  }

  /**
   * 点击编辑
   * @param id - 唯一值
   */
  const onUpdate = async (id: string) => {
    try {
      setCreateOpen(true)
      setCreateTitle(EDIT_TITLE(id))
      setCreateId(id)
      setCreateLoading(true)
      const { data: { data } } = await getUserById(id as string)
      handleGetRoles().then(r => {}) // 获取角色
      handleGetDept().then(r => {}) // 获取部门
      setCreateData(data)
    } finally {
      setCreateLoading(false)
    }
  }

  /** 表格提交 */
  const createSubmit = () => {
    createFormRef.current?.handleSubmit()
  }

  /** 关闭新增/修改弹窗 */
  const closeCreate = () => {
    setCreateOpen(false)
  }

  /** 获取表格数据 */
  const getPage = () => {
    const formData = searchFormRef.current?.getFieldsValue() || {}
    const params = { ...formData, pageIndex, pageSize }
    handleSearch(params)
      .then(r =>{})
  }

  /**
   * 新增/编辑提交
   * @param values - 表单返回数据
   */
  const handleCreate = async (values: IFormData) => {
    try {
      setCreateLoading(true)
      const functions = () => createId ? updateUser(createId, values) : createUser(values)
      const { data } = await functions()
      handleGetRoles().then(r => {}) // 获取角色
      handleGetDept().then(r => {}) // 获取部门
      message.success(data?.message || '操作成功')
      setCreateOpen(false)
      getPage()
    } finally {
      setCreateLoading(false)
    }
  }
  /*
  * 查询角色列表
  * */
  const handleGetRoles = async () => {
    const {data} = await getAllRoles()
    const _res: IConstant[] = []
    if (data.data) {
        for (let i=0;i<data.data.length;i++) {
          const item: IConstant = {label: data.data[i]['roleName'] as string, value: data.data[i]['id'] as unknown as number}
          _res.push(item)
        }
      setRoles(_res)
    }
  }
  /*
  * 获取部门列表
  */
  const handleGetDept = async () => {
    const {data} = await getAllDept()
    const _res: IConstant[] =[]
    if (data.data) {
      for (let i=0;i<data.data.length;i++) {
        const item: IConstant = { label: data.data[i]['deptName'] as string, value: data.data[i]['id'] as unknown as number}
        _res.push(item)
      }
      setDept(_res)
    }
  }

  /**
   * 点击删除
   * @param id - 唯一值
   */
  const onDelete = async (id: string) => {
    try {
      setLoading(true)
      const { data } = await deleteUser(id as string)
      if (data?.code === 200) {
        message.success(data?.message || '删除成功')
        getPage()
      }
    } finally {
      setLoading(false)
    }
  }

  /**
   * 处理分页
   * @param pageIndex - 当前页数
   * @param pageSize - 每页条数
   */
  const onChangePagination = (pageIndex: number, pageSize: number) => {
    setPageIndex(pageIndex)
    setPageSize(pageSize)
    const formData = searchFormRef.current?.getFieldsValue()
    handleSearch({...formData, pageIndex, pageSize})
      .then (r =>{})
  }

  /**
   * 渲染操作
   * @param _ - 当前值
   * @param record - 当前行参数
   */
  const optionRender: ITableOptions<object> = (_, record) => (
    <>
      {
        pagePermission.update &&
        <UpdateBtn
          className='mr-5px'
          isLoading={isLoading}
          onClick={() => onUpdate((record as IRowData).id)}
        />
      }
      {
        pagePermission.delete &&
        <DeleteBtn
          className='mr-5px'
          isLoading={isLoading}
          handleDelete={() => onDelete((record as IRowData).id)}
        />
      }
    </>
  )

  return (
    <PermissionWrapper requiredPermissions={{actions: "admin:sysUser:list"}}>
      <>
        <BasicSearch
          formRef={searchFormRef}
          list={searchList}
          data={initSearch}
          isLoading={isLoading}
          isCreate={pagePermission.create}
          onCreate={onCreate}
          handleFinish={onSearch}
        />

        <BasicTable
          loading={isLoading}
          columns={tableColumns(optionRender, roles, dept)}
          dataSource={tableData}
        />

        <BasicPagination
          disabled={isLoading}
          current={pageIndex}
          pageSize={pageSize}
          total={total}
          onChange={onChangePagination}
        />

        <BasicModal
          title={createTitle}
          open={isCreateOpen}
          confirmLoading={isCreateLoading}
          onOk={createSubmit}
          onCancel={closeCreate}
        >
          <BasicForm
            formRef={createFormRef}
            list={createList(roles, dept)}
            data={createData}
            labelCol={{ span: 6 }}
            handleFinish={handleCreate}
          />
        </BasicModal>
      </>
    </PermissionWrapper>
  )
}

export default Page

// src/pages/admin/sysUser/index.vue
<template>
  <BasicContent :isPermission="checkPermission(pagePermission.list)">
    <template #top>
      <BasicSearch
        :list="searchList"
        :data="searchData"
        :isLoading="isLoading"
        @handleFinish="handleSearch"
        :is-clear="false"
      />
    </template>
    <BtnRow>
      <CreateBtn
        v-if="checkPermission(pagePermission.create)"
        @click="onCreate"
      />
    </BtnRow>
    <BasicTable
      :data="tableData"
      :columns="tableColumns(roleList, deptList)"
      :isLoading="isLoading"
      :pagination="{
        current: pagination.pageIndex,
        pageSize: pagination.pageSize,
        total: pagination.total,
        onChange: handlePagination,
      }"
    >
      <template v-slot:operate="{ record }">
        <UpdateBtn type="primary" size="small" :loading="isCreateLoading" v-if="checkPermission(pagePermission.update)" @click="onUpdate(record)" >编辑</UpdateBtn>
        <DeleteBtn type="primary" danger class="ml-2px" size="small" v-if="checkPermission(pagePermission.delete)" :message="'确定要删除当前用户' + record?.username + '?'" @click="handleDelete(record)">删除</DeleteBtn>
      </template>
    </BasicTable>
  </BasicContent>
  <BasicModal
    v-model:isOpen="creates.isOpen"
    :isLoading="isCreateLoading"
    :title="creates.title"
    @handleFinish="createSubmit"
    @handleCancel="onCloseCreate"
  >
    <BasicForm
      ref="createFormRef"
      :list="createList(roleList, deptList)"
      :labelCol="{ span: 6 }"
      :data="creates.data"
      @handleFinish="handleCreate"
    />
  </BasicModal>
</template>

<script setup lang="ts">
import type { FormData } from '#/form';
import BasicContent from "@/components/Content/BasicContent.vue";
import {createList, pagePermission, searchList, tableColumns} from "@/pages/admin/sysUser/model";
import {checkPermission} from "@/utils/permissions";
import BasicSearch from "@/components/Search/BasicSearch.vue";
import {CreateBtn, DeleteBtn, UpdateBtn} from "@/components/Buttons";
import {ref, shallowRef, reactive, onActivated, onMounted} from "vue";
import {BasicFormProps} from "@/components/Form/model";
import {CreateData, PaginationData, TableData} from "#/public";
import {ADD_TITLE, EDIT_TITLE} from "@/utils/config";
import {createUser, deleteUser, getUserById, getUserPage, updateUser} from "@/servers/admin/user";
import BasicTable from "@/components/Table/BasicTable.vue";
import BasicModal from "@/components/Modal/BasicModal.vue";
import BasicForm from "@/components/Form/BasicForm.vue";
import {IConstant} from "@/utils/constants";
import {getAllDept} from "@/servers/admin/dept";
import {getAllRoles} from "@/servers/admin/role";
import {message} from "ant-design-vue";
import {message as messageAPi} from "ant-design-vue/es/components";

// 搜索数据
const searchData = ref<FormData>({});
const isLoading = ref(false);
const isCreateLoading = ref(false);
const roleList = ref<IConstant[]>([]);
const deptList = ref<IConstant[]>([]);
const createFormRef = shallowRef<BasicFormProps>();
// 表格数据
const tableData = ref<TableData[]>([]);
// 分页数据
const pagination = reactive<PaginationData>({
  total: 0,
  pageIndex: 1,
  pageSize: 20,
});

// 初始化新增数据
const initCreate = {
  // status: 1,
  // user: { name: { test: '1234' } }
};

// 新增数据
const creates = reactive<CreateData>({
  id: '',
  isOpen: false,
  title: ADD_TITLE,
  data: initCreate
});

onActivated(() => {
  getPage();
});

onMounted(() => {
  handleGetAllDept();
  handleGetAllRole();
});

defineOptions({
  name: 'AdminSysUser'
});

/** 点击新增 */
const onCreate = () => {
  creates.isOpen = !creates.isOpen;
  creates.title = ADD_TITLE;
  creates.id = '';
  creates.data = initCreate;
};

// 新增/编辑提交
const handleCreate = async (values: FormData) => {
  try {
    isCreateLoading.value = true;
    const functions = () => creates.id ? updateUser(creates.id, values) : createUser(values);
    const {code, message} = await functions();
    if (code === 200) {
      creates.id = '';
      creates.isOpen = false;
      creates.data = {...initCreate};
      createFormRef.value?.handleReset();
      messageAPi.success(message || '操作成功');
    }
  } finally {
    getPage().then();
    isCreateLoading.value = false;
  }
};

/** 关闭新增/编辑 */
const onCloseCreate = () => {
  creates.isOpen = false;
};

/** 获取表格数据 */
const getPage = async () => {
  const newPagination = { ...pagination };
  delete newPagination.total;
  const query = { ...newPagination, ...searchData.value };
  try {
    isLoading.value = true;
    const { data: {count, list, pageIndex, pageSize} } = await getUserPage(query);
    tableData.value = list;
    pagination.pageIndex = pageIndex;
    pagination.pageSize = pageSize;
    pagination.total = count;
  } finally {
    isLoading.value = false;
  }
};

/** 表格提交 */
const createSubmit = () => {
  createFormRef.value?.handleSubmit();
};

/**
 * 分页
 * @param page - 当前页
 * @param pageSize - 分页总数
 */
const handlePagination = (page: number, pageSize: number) => {
  pagination.pageIndex = page;
  pagination.pageSize = pageSize;
  getPage();
};

// 搜索提交
const handleSearch = (values: FormData) => {
  searchData.value = values;
  pagination.pageIndex = 1;
  getPage();
};

// 点击编辑
const onUpdate = async (record: FormData) => {
  creates.isOpen = !creates.isOpen;
  creates.id = record.id as string;
  creates.title = EDIT_TITLE('修改用户', record.name as string);
  creates.type = 'update';
  try {
    isCreateLoading.value = true;
    const {code, data} = await getUserById(record.id as string);
    if (code === 200) {
      creates.data = data;
    }
  } finally {
    isCreateLoading.value = false;
  }
};

// 删除任务
const handleDelete = async (record: FormData) => {
  try {
    isLoading.value = true;
    const {code} = await deleteUser(record.id as number);
    if (code === 200) {
      message.success('删除成功');
    }
  } finally {
    getPage().then();
    isLoading.value = false;
  }
};

// 部门列表
const handleGetAllDept = async () => {
  const {data, code} = await getAllDept();
  const _res: IConstant[] = [];
  if (code === 200) {
    for (let i = 0;i < data.length;i++) {
      const item: IConstant = { label: data[i].deptName as string, value: data[i].id as unknown as number};
      _res.push(item);
    }
  }
  deptList.value = _res;
};

// 角色列表
const handleGetAllRole = async () => {
  const {data, code} = await getAllRoles();
  const _res: IConstant[] = [];
  if (code === 200) {
    for (let i = 0;i < data.length;i++) {
      const item: IConstant = { label: data[i].roleName as string, value: data[i].id as unknown as number};
      _res.push(item);
    }
  }
  roleList.value = _res;
};

</script>
