// src/pages/admin/sysMenu/index.tsx
import type { IFormData } from '#/form'
import type { RootState } from '@/stores'
import type { IPagePermission, ITableOptions } from '#/public'
import type { IFormFn } from '@/components/Form/BasicForm'
import { useCallback, useEffect, useRef, useState } from 'react'
import { searchList, createList, tableColumns } from './model'
import {Button, message, RadioChangeEvent, TransferProps} from 'antd'
import { useTitle } from '@/hooks/useTitle'
import { useSelector } from 'react-redux'
import {CheckPermission} from '@/utils/permissions'
import { ADD_TITLE, EDIT_TITLE } from '@/utils/config'
import { UpdateBtn, DeleteBtn } from '@/components/Buttons'
import {
  getMenuPage,
  getMenuById,
  createMenu,
  updateMenu,
  deleteMenu, getMenuList
} from '@/servers/admin/menu'
import  {getApisList} from "@/servers/admin/apis"
import BasicSearch from '@/components/Search/BasicSearch'
import BasicModal from '@/components/Modal/BasicModal'
import BasicForm from '@/components/Form/BasicForm'
import BasicTable from '@/components/Table/BasicTable'
import BasicPagination from '@/components/Pagination/BasicPagination'
import PermissionWrapper from "@/components/PermissionWrapper"
import {IConstant} from "@/utils/constants"

// 当前行数据
interface IRowData {
  id: string;
  menuType: string;
}

// 初始化搜索数据
const initSearch = {
  pageIndex: 1,
  pageSize: 20
}

// 初始化新增数据
const initCreate = {
  parentId: '',
  menuType: '',
}

function Page() {
  useTitle('菜单管理')
  const searchFormRef = useRef<IFormFn>(null)
  const createFormRef = useRef<IFormFn>(null)
  const [isCreateOpen, setCreateOpen] = useState(false)
  const [isLoading, setLoading] = useState(false)
  const [isCreateLoading, setCreateLoading] = useState(false)
  const [createTitle, setCreateTitle] = useState(ADD_TITLE)
  const [createId, setCreateId] = useState('')
  const [createData, setCreateData] = useState<IFormData>(initCreate)
  const [page, setPage] = useState(initSearch.pageIndex)
  const [pageSize, setPageSize] = useState(initSearch.pageSize)
  const [total, setTotal] = useState(0)
  const [tableData, setTableData] = useState<IFormData[]>([])
  const userInfo = useSelector((state: RootState) => state.user.userInfo)
  const [menus, setMenus] = useState<IConstant[]>([])
  const [menType, setMenuType] = useState('')
  const [apis, setApis] = useState<IConstant[]>([])
  const [targetApi, setTargetApi] = useState<number[]>([])

  // 权限
  const pagePermission: IPagePermission = {
    page: CheckPermission("admin:sysMenu:query", userInfo.permissions),
    create: CheckPermission("admin:sysMenu:add", userInfo.permissions),
    update: CheckPermission("admin:sysMenu:edit", userInfo.permissions),
    delete: CheckPermission("admin:sysMenu:delete", userInfo.permissions),
  }

  /**
   * 点击搜索
   * @param values - 表单返回数据
   */
  const onSearch = (values: IFormData) => {
    setPage(1)
    handleSearch({ pageIndex: 1, pageSize, ...values }).then(r => {})
  }
  /*
  * 设置Transfer target值
  * */
  const onChangeTargetApi = (value: string[]) => {
      setTargetApi(value as unknown as number[])
  }

  /**
   * 处理搜索
   * @param values - 表单返回数据
   */
  const handleSearch = useCallback(async (values: IFormData) => {
    try {
      setLoading(true)
      const { data: { data } } = await getMenuPage(values)
      setTotal(data.length)
      setTableData(data)
    } finally {
      setLoading(false)
    }
  }, [])

  // 首次进入自动加载接口数据
  useEffect(() => {
    if (pagePermission.page) handleSearch({ ...initSearch }).then(r => {})
    handleGetMuns().then(r => {})
    handleGetApiList().then(r => {})
  }, [handleSearch, pagePermission.page])

  // 更新菜单类型
  const handleSetMuns = (e: RadioChangeEvent) => {
      setMenuType(e.target.value)
  }

  // 获取菜单列表
  const handleGetMuns = async () => {
    const {data} = await getMenuList()
    if (data.data) {
      data.data.unshift({ label: "主类目", value: 0, children: []})
      // @ts-ignore
      setMenus(data.data)
    }
  }

  // 获取API接口列表
  const handleGetApiList = async () => {
    const {data} = await getApisList()
    if (data.data) {
      setApis(data.data)
    }
  }

  /** 点击新增 */
  const onCreate = (record?: IRowData) => {
    setCreateOpen(true)
    setCreateTitle(ADD_TITLE)
    setCreateId('')
    if (record?.id !== undefined) {
      initCreate.parentId = record.id
      initCreate.menuType = record.menuType
      setCreateData(initCreate)
      setMenuType(record.menuType)
    }
  }

  /**
   * 点击编辑
   * @param record
   */
  const onUpdate = async (record: IRowData) => {
    try {
      setCreateOpen(true)
      setCreateTitle(EDIT_TITLE(record.id))
      setCreateId(record.id)
      setCreateLoading(true)
      const { data: { data } } = await getMenuById(record.id)
      setCreateData(data)
      setTargetApi(data.apis)
    } finally {
      setMenuType(record.menuType)
      setCreateLoading(false)
    }
  }

  /** 表单提交 */
  const createSubmit = () => {
    createFormRef.current?.handleSubmit()
  }

  /** 关闭新增/修改弹窗 */
  const closeCreate = () => {
    setCreateOpen(false)
    initCreate.parentId = '' // 添加时重新设置父级菜单
    setCreateData(initCreate)
  }

  /** 获取表格数据 */
  const getPage = () => {
    const formData = searchFormRef.current?.getFieldsValue() || {}
    const params = { ...formData, page, pageSize }
    handleSearch(params).then(r => {})
  }

  /**
   * 新增/编辑提交
   * @param values - 表单返回数据
   */
  const handleCreate = async (values: IFormData) => {
    try {
      setCreateLoading(true)
      values.apis = targetApi // 修改API
      const functions = () => createId ? updateMenu(createId, values) : createMenu(values)
      const { data } = await functions()
      message.success(data?.message || '操作成功')
      setCreateOpen(false)
      getPage()
    } finally {
      setCreateLoading(false)
    }
  }

  /**
   * 点击删除
   * @param id - 唯一值
   */
  const onDelete = async (id: string) => {
    try {
      setLoading(true)
      const { data } = await deleteMenu(id as string)
      if (data?.code === 200) {
        message.success(data?.message || '删除成功')
        getPage()
      }
    } finally {
      setLoading(false)
    }
  }

  /*
  * 穿梭框搜索条件
  * */
  const filterOption = (inputValue: string, option: IConstant) =>
    option.label?.indexOf(inputValue) > -1;

  /**
   * API接口穿梭框参数
   */
  const transferProps: TransferProps<IConstant> = {
    dataSource: apis,
    showSearch: true,
    filterOption: filterOption,
    targetKeys: (targetApi as unknown as string[]),
    onChange: onChangeTargetApi,
    rowKey:  (item) => item.id as unknown as string,
    render: (item) => item.label
  }

  /**
   * 处理分页
   * @param page - 当前页数
   * @param pageSize - 每页条数
   */
  const onChangePagination = useCallback((page: number, pageSize: number) => {
    setPage(page)
    setPageSize(pageSize)
    const formData = searchFormRef.current?.getFieldsValue()
    handleSearch({...formData, page, pageSize})
      .then (r =>{})
  }, [handleSearch])

  /**
   * 渲染操作
   * @param _ - 当前值
   * @param record - 当前行参数
   */
  const optionRender: ITableOptions<object> = (_, record) => (
    <>
      {
        pagePermission.create === true &&
        <Button
          className='mr-5px'
          type={'primary'}
          onClick={() => onCreate(record as IRowData)}
        >
          子菜单
        </Button>
      }
      {
        pagePermission.update === true &&
        <UpdateBtn
          className='mr-5px'
          isLoading={isLoading}
          onClick={() => onUpdate((record as IRowData))}
        />
      }
      {
        pagePermission.delete === true &&
        <DeleteBtn
          className='mr-5px'
          isLoading={isLoading}
          handleDelete={() => onDelete((record as IRowData).id)}
        />
      }
    </>
  )

  return (
    <PermissionWrapper requiredPermissions={{actions: "admin:sysMenu:list"}}>
      <>
        <BasicSearch
          formRef={searchFormRef}
          list={searchList}
          data={initSearch}
          isLoading={isLoading}
          isCreate={pagePermission.create}
          onCreate={onCreate}
          handleFinish={onSearch}
        />
        <BasicTable
          loading={isLoading}
          columns={tableColumns(optionRender)}
          dataSource={tableData}
        />

        <BasicPagination
          disabled={isLoading}
          current={page}
          pageSize={pageSize}
          total={total}
          onChange={onChangePagination}
        />
        <BasicModal
          width={600}
          title={createTitle}
          open={isCreateOpen}
          confirmLoading={isCreateLoading}
          onOk={createSubmit}
          onCancel={closeCreate}
        >
          <BasicForm
            formRef={createFormRef}
            list={createList(transferProps,menus, menType, handleSetMuns)}
            data={createData}
            labelCol={{ span: 5 }}
            wrapperCol={{ span: 15 }}
            handleFinish={handleCreate}
          />
        </BasicModal>
      </>
    </PermissionWrapper>
  )
}

export default Page

// src/pages/admin/sysMenu/index.vue
<template>
  <BasicContent :isPermission="checkPermission(pagePermission.list)">
    <template #top>
      <BasicSearch
        :list="searchList"
        :data="searchData"
        :isLoading="isLoading"
        @handleFinish="handleSearch"
        :is-clear="false"
      />
    </template>
    <BtnRow>
      <CreateBtn
        v-if="checkPermission(pagePermission.create)"
        @click="onCreate"
      />
    </BtnRow>
    <BasicTable
      :data="tableData"
      :columns="tableColumns()"
      :isLoading="isLoading"
      :pagination="{
        current: pagination.pageIndex,
        pageSize: pagination.pageSize,
        total: pagination.total,
        onChange: handlePagination,
      }"
    >
      <template v-slot:visible="{record}">
        <span v-if="record?.visible !== '1'">
          <a-tag color="success">显示</a-tag>
        </span>
        <span v-else>
          <a-tag color="error">隐藏</a-tag>
        </span>
      </template>
      <template v-slot:operate="{ record }">
        <UpdateBtn type="primary" size="small" :loading="isCreateLoading" v-if="checkPermission(pagePermission.update)" @click="onUpdate(record)" >编辑</UpdateBtn>
        <UpdateBtn type="primary" size="small" class="ml-2px" :loading="isPermissionLoading" v-if="checkPermission(pagePermission.update)" @click="onCreate(record)">子菜单</UpdateBtn>
        <DeleteBtn type="primary" danger class="ml-2px" size="small" v-if="checkPermission(pagePermission.delete)" :message="'确定要删除菜单:' + record?.title + '?'" @click="handleDelete(record)">删除</DeleteBtn>
      </template>
    </BasicTable>
  </BasicContent>
  <BasicModal
    v-model:isOpen="creates.isOpen"
    :isLoading="isCreateLoading"
    :title="creates.title"
    @handleFinish="createSubmit"
    @handleCancel="onCloseCreate"
    width="30%"
  >
    <BasicForm
      ref="createFormRef"
      :list="createList(menuList, apiList, targetKey, menuType, findOption, onChange, handleSetMeu)"
      :labelCol="{ span: 6 }"
      :data="creates.data"
      @handleFinish="handleCreate"
    />
  </BasicModal>
</template>

<script setup lang="ts">
import type {FormData} from '#/form';
import {onActivated, onMounted, reactive, ref, shallowRef} from "vue";
import {checkPermission} from "@/utils/permissions";
import {createList, pagePermission, RowData, searchList, tableColumns} from "@/pages/admin/sysMenu/model";
import BasicTable from "@/components/Table/BasicTable.vue";
import BasicContent from "@/components/Content/BasicContent.vue";
import BasicSearch from "@/components/Search/BasicSearch.vue";
import {CreateBtn, DeleteBtn, UpdateBtn} from "@/components/Buttons";
import {BasicFormProps} from "@/components/Form/model";
import {CreateData, PaginationData, TableData} from "#/public";
import {ADD_TITLE, EDIT_TITLE} from "@/utils/config";
import {createMenu, deleteMenu, getMenuById, getMenuList, getMenuPage, updateMenu} from "@/servers/admin/menu";
import {message, TransferProps} from "ant-design-vue";
import BasicModal from "@/components/Modal/BasicModal.vue";
import BasicForm from "@/components/Form/BasicForm.vue";
import {IConstant} from "@/utils/constants";
import {getApisList} from "@/servers/admin/apis";
import {RadioChangeEvent} from "ant-design-vue/es/radio/interface";
import {TransferItem} from "ant-design-vue/es/transfer";

// 搜索数据
const searchData = ref<FormData>({});
const isLoading = ref(false);
const isCreateLoading = ref(false);
const isPermissionLoading = ref(false);
const menuList = ref<IConstant[]>([]);
const apiList = ref<TransferItem[]>([]);
const targetKey = ref<string[]>([]);
const menuType = ref('');

const createFormRef = shallowRef<BasicFormProps>();
// 表格数据
const tableData = ref<TableData[]>([]);

// 分页数据
const pagination = reactive<PaginationData>({
  total: 0,
  pageIndex: 1,
  pageSize: 20,
});

defineOptions({
  name: 'AdminSysMenu'
});

onActivated(() => {
  getPage();
});

onMounted(() => {
  handleGetMenus();
  handleGetApis();
});

// 初始化新增数据
const initCreate = {
  parentId: '',
  menuType: '',
};

// 新增数据
const creates = reactive<CreateData>({
  id: '',
  isOpen: false,
  title: ADD_TITLE,
  data: initCreate
});

// 搜索提交
const handleSearch = (values: FormData) => {
  searchData.value = values;
  pagination.pageIndex = 1;
  getPage();
};

/** 获取表格数据 */
const getPage = async () => {
  const newPagination = { ...pagination };
  delete newPagination.total;
  const query = { ...newPagination, ...searchData.value };
  try {
    isLoading.value = true;
    const { data } = await getMenuPage(query);
    tableData.value = data;
    // pagination.pageIndex = pageIndex;
    // pagination.pageSize = pageSize;
    pagination.total = data.length;
  } finally {
    isLoading.value = false;
  }
};

/**
 * 分页
 * @param page - 当前页
 * @param pageSize - 分页总数
 */
const handlePagination = (page: number, pageSize: number) => {
  pagination.pageIndex = page;
  pagination.pageSize = pageSize;
  getPage();
};

/** 关闭新增/编辑 */
const onCloseCreate = () => {
  creates.isOpen = false;
};

/** 点击新增 */
const onCreate = (record?: RowData) => {
  creates.isOpen = !creates.isOpen;
  creates.title = ADD_TITLE;
  creates.id = '';
  creates.data = initCreate;
  if (record?.id !== '') {
    initCreate.parentId = record?.id as string;
    initCreate.menuType = record?.menuType as string;
    menuType.value = record?.menuType as string;
  }
};

// 点击编辑
const onUpdate = async (record: RowData) => {
  creates.isOpen = !creates.isOpen;
  creates.id = record.id as string;
  creates.title = EDIT_TITLE('修改菜单', record.id as string);
  creates.type = 'update';
  try {
    isCreateLoading.value = true;
    const {code, data} = await getMenuById(record.id as string);
    if (code === 200) {
      creates.data = data;
      // @ts-ignore
      if (data?.apis.length > 0) {
        // @ts-ignore
        targetKey.value = data.apis.map((item: number) => item.toString());
      }
    }
  } finally {
    menuType.value = record.menuType;
    isCreateLoading.value = false;
  }
};

// 删除任务
const handleDelete = async (record: FormData) => {
  try {
    isLoading.value = true;
    const {code} = await deleteMenu(record.id as number);
    if (code === 200) {
      message.success('删除成功');
    }
  } finally {
    getPage().then();
    isLoading.value = false;
  }
};

/** 表格提交 */
const createSubmit = () => {
  createFormRef.value?.handleSubmit();
};

// 新增/编辑提交
const handleCreate = async (values: FormData) => {
  try {
    isCreateLoading.value = true;
    values.apis = (targetKey.value.map((item: string) => Number(item)));
    const functions = () => creates.id ? updateMenu(creates.id, values) : createMenu(values);
    const {code} = await functions();
    if (code === 200) {
      creates.id = '';
      creates.isOpen = false;
      creates.data = {...initCreate};
      createFormRef.value?.handleReset();
      message.success('操作成功');
    }
  } finally {
    getPage().then();
    isCreateLoading.value = false;
  }
};

// 获取菜单树全量数据
const handleGetMenus = async () => {
  const {data, code} = await getMenuList();
  if (code === 200) {
    data.unshift({ label: "主类目", value: 0, children: []});
    // @ts-ignore
    menuList.value = data;
  }
};

// 获取接口列表
const handleGetApis = async () => {
  const {data, code} = await getApisList();
  if (code === 200) {
    // @ts-ignore
    apiList.value = data;
  }
};

const findOption = (inputValue: string, option: IConstant) => option.label?.indexOf(inputValue) > -1;

const onChange:TransferProps['onChange'] = (keys) => {
  // console.log("onChange=>", keys)
  targetKey.value = keys;
};

const handleSetMeu = (e: RadioChangeEvent) => {
  menuType.value = e.target.value;
};
</script>
